name: pff_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  share: ^2.0.4
  firebase_auth: ^4.2.5
  firebase_core: ^2.15.0
  http: ^0.13.6
  flutter_native_splash: ^2.3.1
  image_picker: ^1.0.1
  syncfusion_flutter_pdfviewer: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter_native_splash:
  color: "#42a5f5"
  image: images/icon.jpg


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpg"
  min_sdk_android: 21



flutter:
  uses-material-design: true

  assets:
    - images/image1.jpg
    - images/image2.jpg
    - images/image3.jpg
    - images/image4.jpg
    - images/image5.jpg
    - images/image6.jpg
    - images/image7.jpg
    - images/image8.jpg
    - images/image9.jpg
    - images/profile.jpg
    - images/fsk.jpg
    - images/icon.jpg
    - images/pdficon.png
    